language: js
version: 0.1.0

platform:
  - target: ubuntu
    version: 14.04
    arch: i686

install:
  -  npm install

api: 0.7.3

package:
  - conf.js
  - eventclient.js
  - feedlyclient.js
  - grunt.js
  - locales/en-GB/messages.pot
  - locales/it-IT/messages.pot 
  - newsapp.js
  - package.json
  - users.json
