language: js
version: 0.1.0

platform:
  - target: ubuntu
    version: 14.04
    arch: i686

install:
    npm install

package:
  - conf.js
  - eventclient.js
  - feedlyclient.js
  - grunt.js
  - locales/  
  - newsapp.js
  - package.json
  - users.json
  - additional_games/
  - games/
